In [2]:
import numpy as np
import pandas as pd

import matplotlib.pyplot as plt
import seaborn as sns

import warnings
warnings.filterwarnings(action='ignore')

# 신경망구현 (라이브러리 X)

In [5]:
# 1차원 배열
X = np.array([1,2,3,4])
np.ndim(X)  # 차원수를 구하는 함수

X.shape[0]  # 배열의 요수 수

(4,)

In [10]:
# 2차원 배열
X = np.array([[1,2],[3,4],[5,6]])

np.ndim(X)
X.shape  # (3,2)  => 3행 2열

(3, 2)

In [18]:
# 행렬의 곱(내적)

X = np.array([[1,2],[3,4]])
Y = np.array([[5,6],[7,8]])
X.shape, Y.shape

np.dot(X,Y)

array([[19, 22],
       [43, 50]])

In [20]:
X = np.array([1,2])
W = np.array([[1,3,5],[2,4,6]])

Y = np.dot(X,W)

In [25]:
# 시그모이드함수

def sigmoid(x):
    return 1/(1+np.exp(-x))

In [31]:
X = np.array([1.0,0.5])
W1 = np.array([[0.1,0.3,0.5],
               [0.2,0.4,0.6]])
B1 = np.array([0.1,0.2,0.3])

H1 = np.dot(X,W1) + B1

Z1 = sigmoid(H1)
Z1

W2 = np.array([[0.1,0.4],[0.2,0.5],[0.3,0.6]])
B2 = np.array([0.1,0.2])
H2 = np.dot(Z1,W2) + B2
Z2 = sigmoid(H2)
Z2

W3 = np.array([[0.1,0.2],[0.2,0.3]])
B3 = np.array([0.1,0.2])
H3 = np.dot(Z2,W3) + B3
H3


array([0.31682708, 0.55655308])

In [42]:
scores = np.array([20,10,1])
exp_s = np.exp(scores)

sum_exp_s = np.sum(exp_s)  # 지수함수의 합

y = exp_s / sum_exp_s
y

array([9.99954597e-01, 4.53978684e-05, 5.60254205e-09])

In [55]:
def reLu(x):
    return np.maximum(0,x)

In [60]:
X = np.array([2,5])
W1 = np.array([[1,4],[2,5],[3,6]])
H1 = np.dot(W1,X)
Z1 = reLu(H1)

W2 = np.array([[1,3,5],[2,4,6]])
H2 = np.dot(W2,Z1)

W3 = np.array([1,2])
np.dot(W3,H2)

1041