In [47]:
import numpy as np
import pandas as pd

In [1]:
# tensorflow.org
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()

Instructions for updating:
non-resource variables are not supported in the long term


In [2]:
# 플레이스홀더: 프로그램 실행 중에 값을 변경할 수 있는 변수를 2개 정의; 데이터를 담는 버퍼와 같은 것…
a = tf.placeholder("float")
b = tf.placeholder("float")
# tf.Variable # = 변수

In [3]:
y = tf.multiply(a,b)
sess = tf.Session() # 그래프 실행을 위해서는 세션이 필요
print(sess.run(y,feed_dict={a:3,b:2})) # Session .run() : 그래프를 실행
# y Node 실행. 
# 노드 y를 노드 a,b를 곱한것이라고 하자.
# run이 실행 되면 y 노드 실행… y노드 실행하려면 a,b 필요… a,b에 값을 전달~feed_dict (코드 역행..?)

6.0


In [4]:
a = tf.constant(3)
with tf.Session() as sess:
    print(a.eval())

3


In [11]:
hello = tf.constant("Hello")
# tf를 실해하기 위한 세션 객체 생성
sess = tf.Session()

print(sess.run(hello))

b'Hello'


In [12]:
## tensor의 Rank와 Shape

3  # Rank(차원) : 0 tensor / Shape : []
[1,2,3]  # Rank(차원) : 1 tensor / Shape : [3]
[[1,2,3], [1,2,3]]  # Rank(차원) : 2 tensor / Shape : [2,3]
[[[1,2,3]],[[4,5,6]]]  # Rank(차원) : 3 tensor / Shape : [2,1,3]

3

In [21]:
a = tf.constant(10)
b = tf.constant(20)

# a + b
sess = tf.Session()
c = tf.add(a,b)

print(sess.run(tf.add(a,b)))
print(sess.run(c))

print(sess.run(a))
print(sess.run(b))
print(sess.run(a+b))

# 세션 닫기
sess.close()

30
30
10
20
30


In [32]:
## placeholder 

a = tf.placeholder(dtype="float")
b = tf.placeholder(tf.float32)

adderNode = a + b

sess = tf.Session()

# 단일 데이터 전달
# print(sess.run(adderNode, feed_dict={a:3, b:4}))

# 여러 데이터 전달
print(sess.run(adderNode, feed_dict={a:[3,30], b:[4,40]}))

[ 7. 70.]


In [38]:
# 전달되어지는 두 값을 받아 더한 결과의 3배를 해 출력

a = tf.placeholder(dtype="float")
b = tf.placeholder(tf.float32)

adderNode = a + b
triple = adderNode * 3

sess = tf.Session()

# 단일 데이터 전달
# print(sess.run(adderNode, feed_dict={a:3, b:4}))

# 여러 데이터 전달
print(sess.run(triple, feed_dict={a:2, b:3}))

sess.close()

15.0


In [45]:
# placeholder에 shape 지정
x = tf.placeholder(tf.float32, [None, 3])

xdata = [[1,2,3], [4,5,6]]
xdata2 = [[1,2], [4,5]]

sess = tf.Session()

print(sess.run(x, feed_dict={x : xdata}))
# print(sess.run(x, feed_dict={x : xdata2}))

sess.close()

[[1. 2. 3.]
 [4. 5. 6.]]


In [58]:
# H(x) = wx + b
# 초기값 지정
# w = tf.Variable(tf.random_normal([2,1]))
w = tf.Variable([[1],[2]])

# 행렬곱 함수
hf = tf.matmul(x, w) + b

In [113]:
# Quiz

xdata = [[1,2,3],  # (2,3)
        [4,5,6]]

x = tf.placeholder(tf.float32)

w = tf.Variable(tf.random_normal([3,1]))
b = tf.Variable(tf.random_normal([1]))

hf = tf.matmul(x, w) + b

sess = tf.Session()

# print(sess.run(hf, feed_dict={x : xdata}))
sess.run(tf.global_variables_initializer())

print(sess.run(w))
print("\n")
print(sess.run(b))
print("\n")
print(sess.run(hf, feed_dict={x:xdata}))

# hf = wx + b
# x의 shape = (2,3)
# w의 shape = (3,1)

[[-1.3634039 ]
 [ 0.80046797]
 [-0.29760155]]


[1.5344743]


[[ 0.87920165]
 [-1.7024108 ]]


# 선형 회귀 모델

In [552]:
xtrain = [80, 95, 97]  # 모의고사 점수 (3명)
ytrain = [82, 90, 98]  # 수   능 점수 (3명)

# 모의고사 70점 학생은 수능 점수가 몇 점일까 ?
# hf = wx + b 
# 82 = ? * 80 + b
# 90 = ? * 95 + b
# 98 = ? * 97 + b

w = tf.Variable(tf.random_normal([1]))
b = tf.Variable(tf.random_normal([1]))

hf = xtrain * w + b
# 세션 열기
sess = tf.Session()
# tf.Variable을 사용하기 위한 구문
sess.run(tf.global_variables_initializer())

print(sess.run([w,b,hf]))

[array([-1.5747062], dtype=float32), array([-0.6221169], dtype=float32), array([-126.59861, -150.21921, -153.36862], dtype=float32)]


In [553]:
hf = xtrain * w + b
cost = tf.reduce_mean(tf.square(hf - ytrain))  # (예측값 - 실제값)합의 제곱에 대한 평균
cost

<tf.Tensor 'Mean_15:0' shape=() dtype=float32>

In [554]:
# 옵티마이져 선택
opt =tf.train.GradientDescentOptimizer(0.00001)
# 경사하강법
train = opt.minimize(cost)

In [555]:
# fit the line
print(sess.run([cost, w, b]))

[54801.61, array([-1.5747062], dtype=float32), array([-0.6221169], dtype=float32)]


In [556]:
sess.run(train)
print(sess.run([cost, w, b]))

[38158.89, array([-1.1487631], dtype=float32), array([-0.617449], dtype=float32)]


In [557]:
for step in range(2001):
    sess.run(train)
    if step % 100 == 0 :
        print(step, sess.run(cost),
             sess.run(w), sess.run(b))

0 26571.287 [-0.7933476] [-0.6135535]
100 9.518012 [0.9977242] [-0.59366935]
200 9.517929 [0.9977213] [-0.59340113]
300 9.517859 [0.9977183] [-0.5931329]
400 9.517787 [0.99771535] [-0.5928647]
500 9.517704 [0.9977125] [-0.5925965]
600 9.517647 [0.9977095] [-0.59232825]
700 9.517573 [0.99770653] [-0.59206]
800 9.51749 [0.9977037] [-0.5917918]
900 9.5174265 [0.99770075] [-0.5915236]
1000 9.517368 [0.9976978] [-0.59125537]
1100 9.517295 [0.99769485] [-0.59098715]
1200 9.517224 [0.99769187] [-0.5907189]
1300 9.517143 [0.99768895] [-0.5904507]
1400 9.517082 [0.997686] [-0.5901825]
1500 9.516988 [0.9976831] [-0.58991426]
1600 9.516931 [0.9976801] [-0.58964604]
1700 9.516856 [0.9976772] [-0.5893778]
1800 9.516799 [0.9976742] [-0.5891096]
1900 9.516705 [0.9976713] [-0.5888414]
2000 9.516643 [0.9976684] [-0.58857316]


In [563]:
# 모의고사 점수가 50번 => 수능점수 ?

yhat = sess.run(w)[0] * 50 + sess.run(b)[0]
print(yhat)

49.29484611749649


In [607]:
df = pd.read_csv('data/carsdata/cars.csv')
df.fillna(0)
df

cylinders = df[' cylinders'].to_list()
hp = df[' hp'].to_list()

In [608]:
# hf = X * w + b

x = cylinders

w = tf.Variable(tf.random_normal([1]))
b = tf.Variable(tf.random_normal([1]))

hf = x * w + b

sess = tf.Session()

sess.run(tf.global_variables_initializer())

print(sess.run([hf, w,b]))

[array([-4.590158 , -1.7227635, -4.590158 , -4.590158 , -1.7227635,
       -4.590158 , -4.590158 , -4.590158 , -2.4396122, -1.7227635,
       -1.7227635, -1.7227635, -4.590158 , -4.590158 , -3.1564608,
       -4.590158 , -1.7227635, -4.590158 , -1.7227635, -1.7227635,
       -1.7227635, -1.7227635, -3.1564608, -4.590158 , -1.7227635,
       -1.7227635, -1.7227635, -4.590158 , -3.1564608, -1.7227635,
       -1.7227635, -3.1564608, -1.7227635, -3.1564608, -1.7227635,
       -3.1564608, -1.7227635, -1.0059149, -4.590158 , -3.1564608,
       -3.1564608, -4.590158 , -3.1564608, -3.1564608, -4.590158 ,
       -1.7227635, -4.590158 , -1.7227635, -1.7227635, -3.1564608,
       -4.590158 , -1.7227635, -4.590158 , -1.7227635, -4.590158 ,
       -4.590158 , -3.1564608, -1.7227635, -1.7227635, -4.590158 ,
       -3.1564608, -1.7227635, -3.1564608, -1.7227635, -4.590158 ,
       -3.1564608, -1.7227635, -1.7227635, -1.7227635, -4.590158 ,
       -3.1564608, -1.7227635, -1.7227635, -1.7227635, -1.722

In [615]:
cost = tf.reduce_mean(tf.square(hf - hp))  # (예측값 - 실제값)합의 제곱에 대한 평균

print(sess.run(cost))

# 옵티마이져 선택
opt = tf.train.GradientDescentOptimizer(0.01)
# 경사하강법
train = opt.minimize(cost)

for step in range(2001):
    sess.run(train)
    if step % 100 == 0 :
        print(step, sess.run(cost),
             sess.run(w), sess.run(b))

testset = [10,12,14,18]
for test in testset :
    yhat = sess.run(w)[0] * test + sess.run(b)[0]
    print(yhat)

466.8451
0 466.8451 [19.74758] [-4.0295606]
100 466.8451 [19.74758] [-4.0295606]
200 466.8451 [19.74758] [-4.0295606]
300 466.8451 [19.74758] [-4.0295606]
400 466.8451 [19.74758] [-4.0295606]
500 466.8451 [19.74758] [-4.0295606]
600 466.8451 [19.74758] [-4.0295606]
700 466.8451 [19.74758] [-4.0295606]
800 466.8451 [19.74758] [-4.0295606]
900 466.8451 [19.74758] [-4.0295606]
1000 466.8451 [19.74758] [-4.0295606]
1100 466.8451 [19.74758] [-4.0295606]
1200 466.8451 [19.74758] [-4.0295606]
1300 466.8451 [19.74758] [-4.0295606]
1400 466.8451 [19.74758] [-4.0295606]
1500 466.8451 [19.74758] [-4.0295606]
1600 466.8451 [19.74758] [-4.0295606]
1700 466.8451 [19.74758] [-4.0295606]
1800 466.8451 [19.74758] [-4.0295606]
1900 466.8451 [19.74758] [-4.0295606]
2000 466.8451 [19.74758] [-4.0295606]
193.44623517990112
232.94139432907104
272.43655347824097
351.4268717765808
